### ISSUE TITLE
按要求填了，还是显示缺少参数，球球帮看看

### ISSUE THREAD

**Issue by atriatri20** [NumberSir/nonebot_plugin_baidutranslate#3]
![image](https://user-images.githubusercontent.com/21164819/199263225-b6d02b94-edd7-471f-aa3c-220bf4530b17.png)
Traceback (most recent call last):
  File "f:\test\zbp_windows_amd64\nb2\bot.py", line 46, in <module>
    nonebot.run(app="__mp_main__:app")
  File "C:\Users\18749\AppData\Local\Programs\Python\Python38\lib\site-packages\nonebot\__init__.py", line 273, in run
    get_driver().run(*args, **kwargs)
  File "C:\Users\18749\AppData\Local\Programs\Python\Python38\lib\site-packages\nonebot\drivers\fastapi.py", line 172, in run
    uvicorn.run(
  File "C:\Users\18749\AppData\Local\Programs\Python\Python38\lib\site-packages\uvicorn\main.py", line 576, in run
    server.run()
  File "C:\Users\18749\AppData\Local\Programs\Python\Python38\lib\site-packages\uvicorn\server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\18749\AppData\Local\Programs\Python\Python38\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\18749\AppData\Local\Programs\Python\Python38\lib\asyncio\base_events.py", line 603, in run_until_complete
    self.run_forever()
  File "C:\Users\18749\AppData\Local\Programs\Python\Python38\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "C:\Users\18749\AppData\Local\Programs\Python\Python38\lib\asyncio\base_events.py", line 570, in run_forever
    self._run_once()
  File "C:\Users\18749\AppData\Local\Programs\Python\Python38\lib\asyncio\base_events.py", line 1859, in _run_once
    handle._run()
  File "C:\Users\18749\AppData\Local\Programs\Python\Python38\lib\asyncio\events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\18749\AppData\Local\Programs\Python\Python38\lib\site-packages\nonebot\message.py", line 142, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
> File "C:\Users\18749\AppData\Local\Programs\Python\Python38\lib\site-packages\nonebot\message.py", line 186, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "C:\Users\18749\AppData\Local\Programs\Python\Python38\lib\site-packages\nonebot\internal\matcher.py", line 716, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "C:\Users\18749\AppData\Local\Programs\Python\Python38\lib\site-packages\nonebot\internal\matcher.py", line 688, in simple_run
    await handler(
  File "C:\Users\18749\AppData\Local\Programs\Python\Python38\lib\site-packages\nonebot\dependencies\__init__.py", line 108, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "C:\Users\18749\AppData\Local\Programs\Python\Python38\lib\site-packages\nonebot_plugin_baidutranslate\__init__.py", line 27, in _
    await translate.send(await translate_msg(_from_to, _query), at_sender=True)
  File "C:\Users\18749\AppData\Local\Programs\Python\Python38\lib\site-packages\nonebot_plugin_baidutranslate\data_source.py", line 56, in translate_msg
    raise EXCEPTIONS[json_data['error_code']]
nonebot_plugin_baidutranslate.utils.exceptions.BaiduMissingArgException: 错误代码：54000        错误信息：请检查是否少传参数 ...

改成中文双引号，又显示是appid是否开通，不知道什么原因了

**Comment by 1v7w** [comment]
我已修复，可以先把修复后的保存下载手动载入，等待pr通过后再更新
[修复后的版本](https://github.com/Guyiiyu/nonebot_plugin_baidutranslate)
